version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - run: npm install
      - run: npm start
workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 2-31/2 * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
