name: Stream

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
      - name: Run ollama
        run: |
          ollama
          ollama serve &
          until curl --output /dev/null --silent --head --fail http://127.0.0.1:11434; do
              printf '.'
              sleep 5
          done
          ollama pull llama3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: npm install
      - name: Run index.js
        run: |
          ollama serve &
          node index.js
      - name: Commit data.json
        if: always()
        run: |
          cd ./globe
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json
          git commit -m 'Update data.json'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}